### ISSUE TITLE
In place Arduino data conversion

### ISSUE THREAD

**Issue by rtu-dataframe** [hassebjork/WeatherReader#3]
Hi, i was wondering how to do the in place data conversion directly on Arduino.

Let me explain, i want to use it as mqtt client and i want that the readed hex string from sensor will be unpacked, parsed and ready to go to my MQTT broker, for example, i read this string: F26C1C4000 but i don't understood how i can unpack it.

I'm currently stuck on the bit shifting, data casting.

Thanks

**Comment by hassebjork** [comment]
The bit shifting is very dependent on what sensor you have. The unpacking
of the code string is all in the server/parser.c, which was written for a
Rasperry Pi.

I used Arudino Nano to listen in on the sensor messages, but it is much to
small to fit decoding of multiple sensors into it. I guess you will use
something more powerful, such as an ESP8266.

In server/parser.c you see links in the comments to the decoding info I
used for each sensor. Check it out!

Best regards
Hasse Bjork

**Comment by rtu-dataframe** [comment]
Hi Hasse, 

I'm currently working on a ESP32 MCU and i'm interested to use this one in order to get data from my Ventus WS155 device.

I've looked at the server/parser.c and i've focused on the respective Ventus decoder/sensor data reader, as you can see below, i've tried to do in place conversion, but i think that i'm doing something wrong:


```
void reportSerial (const char* s, class DecodeOOK& decoder) {
  if ( decoder.checkSum() ) {
    byte pos;
    byte* data = decoder.getData(pos);
    Serial.print(s);
    Serial.print(" -> DATA: \n");
    char* hex_data;
    for (byte i = 0; i < pos; ++i) {
      char first_hex = data[i] >> 4;
      char padding_hex = data[i] & 0x0F;

      hex_data[i] = first_hex;
      hex_data[i+1] = padding_hex;

      Serial.print(first_hex, HEX);
      Serial.print(padding_hex, HEX);
    }

    float rain = (( hex_data[4] << 4 | hex_data[5] ) | (hex_data[6]  << 4 | hex_data[7] ) << 8 ) * .25; //This is the Rain formula used on the RPI Server
    Serial.print( "\n" );
    Serial.print( "RAIN:" );
    Serial.print(rain); //Prints 0
    Serial.print( "\n" );

  }
  decoder.resetDecoder();
}

```

**Comment by hassebjork** [comment]
Have you read the documentation in the comment (
http://www.tfd.hu/tfdhu/files/wsprotocol/auriol_protocol_v20.pdf)?

F2 6C 1C40 00
F2 is a random id, it normally changes every time you change battery
6C (or EC) identifies this as a rain gauge. 6C battery level above 2.6
Volt. EC battery level below 2.6 Volts
1-C-4-0 is the accumulated rain, since battery change. Each 4 bit sequence
in reversed order, so actually 8-3-2-0
00 is the checksum (only the first 4 bits)

I have not done any programming in a long while, certainly not on this
project (5 years). Here is a guess on solving this. It might put you on the
right track. I have not compiled tested the code in any way!!

float rain = -300.0;
void reportSerial (const char* s, class DecodeOOK& decoder) {
  if ( decoder.checkSum() ) {
    byte pos;
    long temp = 0;
    byte* data = decoder.getData(pos);
    Serial.print(s);
    Serial.print(" -> DATA: \n");
    for (byte i = 0; i < pos; ++i) {
      char first_hex = data[i] >> 4;
      char padding_hex = data[i] & 0x0F;
      if ( i == 2 || i == 3 )
        temp = ( temp << 8 )             | ( reverse_bits_lookup[
first_hex ] << 4 )
            | reverse_bits_lookup[ padding_hex ];

      Serial.print(first_hex, HEX);
      Serial.print(padding_hex, HEX);
    }
    rain = temp * .25;    Serial.print( "\n" );
    Serial.print( "RAIN:" );
    Serial.print(rain); //Prints 0
    Serial.print( "\n" );

  }
  decoder.resetDecoder();
}


Hope this will put you on the right track!

Running this as MQTT, you probably would like the float rain to be a global
variable for reading anytime. The value -300.0 means it is unset, no value
has been read.

Another optimization you could do is a loop, waiting for a signal and then
put the RF or EPS32 to sleep / pwr down for 140 seconds. Normally there is
aprox. 148 seconds between each transmit. If it rains, there is an
immediate  transmit and the next scheduled will be in aprox. 148 seconds. A
weather station on battery keeps track of the next expected transmit from
all sensors and is put to sleep in wait for the next transmit. This saves a
lot of power.

Running the RF-decoder on a Raspberry Pi kept the CPU busy to 99%, so I
moved the RF-listening and decoding to an Arduino Nano. The Raspberry Pi
did the data decoding, storing and sending it to an external MySQL server
for storage. The ESP might have trouble sending WiFi signals, if the CPU is
too busy.

Good Luck

Hasse Bjork

**Comment by rtu-dataframe** [comment]
Thanks, i'll try to manage some experiments to that.

I'll keep you posted!
Simone
